contents:
  - name: 图论
    directory: 图论
  - name: 数学
    directory: 数学
  - name: 数据结构
    directory: 数据结构
  - name: 动态规划
    directory: 动态规划
  - name: 字符串
    directory: 字符串
  - name: 杂
    directory: 杂