contents:
  - name: 01BFS
    code: 01BFS.cpp
  - name: Bellman-ford
    code: Bellman-ford.cpp
  - name: dfs判二分图
    code: dfs判二分图.cpp
  - name: Dijkstra
    code: Dijkstra.cpp
  - name: Floyd
    code: Floyd.cpp
  - name: Floyd找最小环
    code: Floyd找最小环.cpp
  - name: Kruskal
    code: Kruskal.cpp
  - name: Prim
    code: Prim.cpp
  - name: SPFA
    code: SPFA.cpp
  - name: 边双联通分量
    code: 边双联通分量.cpp
  - name: 并查集判二分图
    code: 并查集判二分图.cpp
  - name: 点双联通分量
    code: 点双联通分量.cpp
  - name: 哈密顿路径
    code: 哈密顿路径.cpp
  - name: 链式前向星
    code: 链式前向星.cpp
  - name: 缩点
    code: 缩点.cpp
  - name: 拓扑排序
    code: 拓扑排序.cpp
  - name: 同余最短路
    code: 同余最短路.cpp
  - name: 网络流
    code: 网络流.cpp
  - name: 匈牙利算法
    code: 匈牙利算法.cpp
  - name: 找割点
    code: 找割点.cpp
  - name: 最长路
    code: 最长路.cpp









